Update mongolid version 3
leroy-merlin-br/mongolid-passport pull request #21
Opened 2022-02-21 19:20 UTC by djonasm

2022-05-04 13:10 UTC, orlandocavassani requested changes, later dismissed

2022-05-04 13:10 UTC, orlandocavassani commented on src/Client.php
> +    public function setSecretAttribute($value): string
Does Mongolid use the return of a setter to fill a field?

2022-05-04 13:10 UTC, orlandocavassani commented on src/Console/HashCommand.php
> +                $client->setSecretAttribute($client->secret);
Using fill is more intuitive than calling setter directly, and works with the syntax `$client->secret = 'some-secret';`. I would use fill.

But, if you don't want to change it, you'll have to fix the `ClientCommand` and look for other necessary changes.

2022-07-15 14:15 UTC, diegofelix approved these changes

2022-07-15 16:54 UTC, henrique221 approved these changes

2022-09-15 12:31 UTC, merged