chore(deps): bump mongolid and mongolid-laravel to version 3.4
leroy-merlin-br/mongolid-passport pull request #27
Opened 2022-12-21 14:17 UTC by orlandocavassani

### Description
Bump _mongolid_ and _mongolid-laravel_ to version 3.4 with support to PHP 8.1.

2022-12-22 12:11 UTC, Vagnerlg approved these changes

2022-12-22 12:15 UTC, diegofelix requested changes

2022-12-22 12:15 UTC, diegofelix commented on src/ApiTokenCookieFactory.php
> +        ], Passport::tokenEncryptionKey($this->encrypter), 'HS256');
We need to test it before merge.

2022-12-23 14:56 UTC, orlandocavassani commented on src/ApiTokenCookieFactory.php
> +        ], Passport::tokenEncryptionKey($this->encrypter), 'HS256');
We tested, and it works fine.

2023-01-02 14:30 UTC, diegofelix approved these changes

2023-01-02 16:25 UTC, merged