Update passport to version 7.0
leroy-merlin-br/mongolid-passport pull request #8
Opened 2018-12-03 17:03 UTC by diegofelix

2018-12-04 11:20 UTC, vitorbari requested changes

2018-12-04 11:20 UTC, vitorbari commented on src/Client.php
> +        return $this->belongsTo(
Use mongolid method here

2018-12-04 11:20 UTC, vitorbari commented on src/Console/ClientCommand.php
> +    protected function createClientCredentialsClient(ClientRepository $clients)
The `$allowedScopes` steps should be moved into this method.

2018-12-04 12:26 UTC, diegofelix commented on src/Client.php
> +        return $this->belongsTo(
Done

2018-12-04 12:26 UTC, diegofelix commented on src/Console/ClientCommand.php
> +    protected function createClientCredentialsClient(ClientRepository $clients)
Done

2018-12-04 15:56 UTC, ravanscafi commented on .travis.yml
> +  - phpenv config-rm xdebug.ini || true
why? without this we will have no coverage metrics

![image](https://user-images.githubusercontent.com/6104262/49454483-62561d80-f7cc-11e8-9c94-7588811c89ca.png)

2018-12-19 20:16 UTC, ravanscafi approved these changes

2018-12-19 20:18 UTC, merged